package entity;

import core.DB;
import java.sql.*;
import java.util.*;

public class MenuItemDAO implements DAO<MenuItem> {

    /**
     * Fetch a single menu item by its ID
     * Returns Optional<MenuItem> so caller can check if it exists
     */
    @Override
    public Optional<MenuItem> get(int id) {
        DB db = DB.getInstance();
        try {
            String sql = "SELECT * FROM OD_MenuItem WHERE Item_ID = ?";
            PreparedStatement stmt = db.getPreparedStatement(sql);
            stmt.setInt(1, id);
            ResultSet rs = stmt.executeQuery();
            MenuItem item = null;
            if (rs.next()) {
                item = new MenuItem(
                        rs.getInt("Item_ID"),
                        rs.getString("Item_Name"),
                        rs.getDouble("Item_Price"),
                        rs.getString("Item_Category")
                );
            }
            return Optional.ofNullable(item);
        } catch (SQLException ex) {
            System.err.println("Error fetching menu item: " + ex);
            return Optional.empty();
        }
    }

     //Returns all menu items in the database
    @Override
    public List<MenuItem> getAll() {
        DB db = DB.getInstance();
        List<MenuItem> items = new ArrayList<>();
        try {
            String sql = "SELECT * FROM OD_MenuItem";
            ResultSet rs = db.executeQuery(sql);
            // Loop through all rows and create MenuItem objects
            while (rs.next()) {
                items.add(new MenuItem(
                        rs.getInt("Item_ID"),
                        rs.getString("Item_Name"),
                        rs.getDouble("Item_Price"),
                        rs.getString("Item_Category")
                ));
            }
        } catch (SQLException ex) {
            System.err.println("Error fetching all menu items: " + ex);
        }
        return items;
    }

    /**
     * Insert a new MenuItem into the database
     * Item_ID is auto-generated by Derby
     */
    @Override
    public void insert(MenuItem item) {
        DB db = DB.getInstance();
        try {
            String sql = "INSERT INTO OD_MenuItem (Item_Name, Item_Price, Item_Category) VALUES (?, ?, ?)";
            PreparedStatement stmt = db.getPreparedStatement(sql);

            stmt.setString(1, item.getName());
            stmt.setDouble(2, item.getPrice());
            stmt.setString(3, item.getCategory());

            int rowInserted = stmt.executeUpdate();

            if (rowInserted > 0) {
                System.out.println("A new menu item was added successfully!");
            }

        } catch (SQLException ex) {
            System.err.println("Error inserting menu item: " + ex);
        }
    }

    // Update a menu item by ID
    @Override
    public void update(MenuItem item) {
        DB db = DB.getInstance();
        try {
            String sql = "UPDATE OD_MenuItem SET Item_Name=?, Item_Price=?, Item_Category=? WHERE Item_ID=?";
            PreparedStatement stmt = db.getPreparedStatement(sql);
            stmt.setString(1, item.getName());
            stmt.setDouble(2, item.getPrice());
            stmt.setString(3, item.getCategory());
            stmt.setInt(4, item.getId());
            int rowsUpdated = stmt.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Menu item updated successfully!");
            }
        } catch (SQLException ex) {
            System.err.println("Error updating menu item: " + ex);
        }
    }

    //Deletes a menu item using its ID
    @Override
    public void delete(MenuItem item) {
        DB db = DB.getInstance();
        try {
            String sql = "DELETE FROM OD_MenuItem WHERE Item_ID = ?";
            PreparedStatement stmt = db.getPreparedStatement(sql);
            stmt.setInt(1, item.getId());
            int rowsDeleted = stmt.executeUpdate();
            if (rowsDeleted > 0) {
                System.out.println("Menu item deleted successfully!");
            }
        } catch (SQLException ex) {
            System.err.println("Error deleting menu item: " + ex);
        }
    }

/**
 * Returns list of column names in OD_MenuItem
 * Used for building table headers in GUI
 */
    @Override
    public List<String> getColumnNames() {
        DB db = DB.getInstance();
        List<String> headers = new ArrayList<>();
        try {
            String sql = "SELECT * FROM OD_MenuItem WHERE Item_ID = -1";
            ResultSet rs = db.executeQuery(sql);
            ResultSetMetaData rsmd = rs.getMetaData();
            int numberCols = rsmd.getColumnCount();
            for (int i = 1; i <= numberCols; i++) {
                headers.add(rsmd.getColumnLabel(i));
            }
        } catch (SQLException ex) {
            System.err.println("Error getting column names: " + ex);
        }
        return headers;
    }
}