package entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import core.DB;

import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

/**
 * OrderDAO handles all CRUD operations for the OD_ORDER table.
 * Uses Derby + Flyway
*/
public class OrderDAO implements DAO<Order> {

    public OrderDAO() {}

    // Fetch a single order by its ORDER_ID
    @Override
    public Optional<Order> get(int id) {
        DB db = DB.getInstance();
        try {
            String sql = "SELECT * FROM OD_ORDER WHERE ORDER_ID = ?";
            PreparedStatement stmt = db.getPreparedStatement(sql);
            stmt.setInt(1, id);
            ResultSet rs = stmt.executeQuery();

            Order order = null;

            // If found, build Order object
            if (rs.next()) {
                order = new Order(
                        rs.getInt("ORDER_ID"),
                        rs.getDouble("ORDER_PRICE"),   // <-- correct decimal
                        rs.getString("ORDER_DATE_TIME"),
                        rs.getString("ITEM_NAME")
                );
            }

            return Optional.ofNullable(order);
        } catch (SQLException ex) {
            System.err.println("Error fetching order: " + ex.getMessage());
            return Optional.empty();
        }
    }

    // Return all orders in the database, ordered by newest first.
    @Override
    public List<Order> getAll() {
        DB db = DB.getInstance();
        List<Order> orders = new ArrayList<>();
        try {
            String sql = "SELECT * FROM OD_ORDER ORDER BY ORDER_ID DESC";
            ResultSet rs = db.executeQuery(sql);

            // Build a list of Order objects
            while (rs.next()) {
                orders.add(new Order(
                        rs.getInt("ORDER_ID"),
                        rs.getDouble("ORDER_PRICE"),   // <-- correct decimal
                        rs.getString("ORDER_DATE_TIME"),
                        rs.getString("ITEM_NAME")
                ));
            }

            return orders;
        } catch (SQLException ex) {
            System.err.println("Error loading orders: " + ex.getMessage());
            return null;
        }
    }

    /**
     * Insert a new order into the table.
     * ORDER_ID is auto-generated by Derby.
     */
    @Override
    public void insert(Order order) {
        DB db = DB.getInstance();
        try {
            String sql = "INSERT INTO OD_ORDER (ORDER_PRICE, ORDER_DATE_TIME, ITEM_NAME) VALUES (?, ?, ?)";
            PreparedStatement stmt = db.getPreparedStatement(sql);

            stmt.setDouble(1, order.getPrice());  // <-- correct decimal value
            stmt.setString(2, order.getDateTime());
            stmt.setString(3, order.getItemName());

            int rowInserted = stmt.executeUpdate();
            if (rowInserted > 0) {
                System.out.println("✅ New order inserted successfully!");
            }
        } catch (SQLException ex) {
            System.err.println("Error inserting order: " + ex.getMessage());
        }
    }

    // Update an existing order's fields based on ORDER_ID
    @Override
    public void update(Order order) {
        DB db = DB.getInstance();
        try {
            String sql = "UPDATE OD_ORDER SET ORDER_PRICE=?, ORDER_DATE_TIME=?, ITEM_NAME=? WHERE ORDER_ID=?";
            PreparedStatement stmt = db.getPreparedStatement(sql);

            stmt.setDouble(1, order.getPrice());   // <-- decimal
            stmt.setString(2, order.getDateTime());
            stmt.setString(3, order.getItemName());
            stmt.setInt(4, order.getID());

            int rowsUpdated = stmt.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("✅ Order updated successfully!");
            }
        } catch (SQLException ex) {
            System.err.println("Error updating order: " + ex.getMessage());
        }
    }

    // Delete an order from the database using ORDER_ID
    @Override
    public void delete(Order order) {
        DB db = DB.getInstance();
        try {
            String sql = "DELETE FROM OD_ORDER WHERE ORDER_ID = ?";
            PreparedStatement stmt = db.getPreparedStatement(sql);
            stmt.setInt(1, order.getID());

            int rowsDeleted = stmt.executeUpdate();
            if (rowsDeleted > 0) {
                System.out.println("✅ Order deleted successfully!");
            }
        } catch (SQLException ex) {
            System.err.println("Error deleting order: " + ex.getMessage());
        }
    }

/**
 * Returns list of column names in OD_ORDER.
 * Used for building table headers in JTable GUI.
 */
    @Override
    public List<String> getColumnNames() {
        DB db = DB.getInstance();
        ResultSet rs = null;
        List<String> headers = new ArrayList<>();

        try {
            String sql = "SELECT * FROM OD_ORDER WHERE ORDER_ID = -1";
            rs = db.executeQuery(sql);
            ResultSetMetaData rsmd = rs.getMetaData();
            int numberCols = rsmd.getColumnCount();

            for (int i = 1; i <= numberCols; i++) {
                headers.add(rsmd.getColumnLabel(i));
            }
            return headers;

        } catch (SQLException ex) {
            System.err.println("Error getting column names: " + ex.getMessage());
            return null;
        }
    }
}
