CREATE TABLE OAKDONUTSDB.OD_MENUITEM (
    ITEM_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_NAME VARCHAR(100) NOT NULL,
    ITEM_PRICE DECIMAL(5, 2) NOT NULL,
    ITEM_CATEGORY VARCHAR(100) NOT NULL
);
