CREATE TABLE OAKDONUTSDB.ORDER_DETAILS (
    DETAIL_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID INT,
    ITEM_ID INT,
    QUANTITY INT,
    FOREIGN KEY (ORDER_ID) REFERENCES OAKDONUTSDB.OD_ORDER(ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES OAKDONUTSDB.OD_MENUITEM(ITEM_ID)
);
